// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using nutridet_ai_api.Models;

#nullable disable

namespace nutridet_ai_api.Migrations
{
    [DbContext(typeof(NutridetAiDbContext))]
    partial class NutridetAiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("nutridet_ai_api.Models.OutputNutrition", b =>
                {
                    b.Property<int>("AiRawId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AiRawId"));

                    b.Property<decimal?>("CarbohydrateG")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("CholesterolMg")
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("EnergyKcal")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("FatG")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("FiberG")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("ProteinG")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("SaturatedFatG")
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("ScanImageId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("SodiumMg")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("SugarG")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("AiRawId");

                    b.HasIndex("ScanImageId")
                        .IsUnique();

                    b.ToTable("OutputNutritions");
                });

            modelBuilder.Entity("nutridet_ai_api.Models.ScanImage", b =>
                {
                    b.Property<int>("ScanImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ScanImageId"));

                    b.Property<decimal?>("AiConfidence")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("AiProvider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConfidenceStatus")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("RawTextResponse")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ScanImageId");

                    b.HasIndex("UserId");

                    b.ToTable("ScanImages");
                });

            modelBuilder.Entity("nutridet_ai_api.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("nutridet_ai_api.Models.OutputNutrition", b =>
                {
                    b.HasOne("nutridet_ai_api.Models.ScanImage", "ScanImage")
                        .WithOne("OutputNutrition")
                        .HasForeignKey("nutridet_ai_api.Models.OutputNutrition", "ScanImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanImage");
                });

            modelBuilder.Entity("nutridet_ai_api.Models.ScanImage", b =>
                {
                    b.HasOne("nutridet_ai_api.Models.User", "User")
                        .WithMany("ScanImages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("nutridet_ai_api.Models.ScanImage", b =>
                {
                    b.Navigation("OutputNutrition")
                        .IsRequired();
                });

            modelBuilder.Entity("nutridet_ai_api.Models.User", b =>
                {
                    b.Navigation("ScanImages");
                });
#pragma warning restore 612, 618
        }
    }
}
